<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Sysc Sysc' => '',
  'Sysc Sysm' => '',
  'Sysc Syss' => '',
  'SyscSysc' => '',
  'SyscSysm' => 'Komponente',
  'SyscSyss' => 'Sistēma',
  'Syss System' => 'Sistēma',
  'Syss Systems' => 'Sistēma',
  'SyssCcmp' => 'Uzņēmums',
  'help.name' => '',
  'help.sysc_deleted' => '',
  'help.sysc_is_parent' => '',
  'help.sysc_level' => '',
  'help.sysc_name' => '',
  'help.sysm_name' => '',
  'help.syss_ccmp_id' => '@@@@',
  'Cancel' => 'Atcelt',
  'Create' => 'Izveidot',
  'Data' => 'Dati',
  'Delete' => 'Dzēst',
  'Do you want to delete this item?' => 'Vai patiešam jūs vēlaties dzēst šo ierakstu?',
  'Fields with <span class="required">*</span> are required.' => 'Ievadlauki ar <span class="required">*</span> ir obligāti.',
  'Invalid request. Please do not repeat this request again.' => 'Kļudains pieprasījums',
  'Manage' => 'Saraksts',
  'Name' => 'Vārds',
  'Relations' => 'Saistītās tabulas',
  'Save' => 'Saglabāt',
  'Search' => 'Meklēt',
  'Sysc' => 'Komponentes',
  'Sysc Components' => 'Komponentes',
  'Sysc Deleted' => 'Dzēsta',
  'Sysc Is Parent' => 'Iz vecāks',
  'Sysc Level' => 'Līmenis',
  'Sysc Name' => 'Nosaukums',
  'Sysm' => 'Ražotāji',
  'Sysm Name' => 'Nosaukums',
  'Sysm Sysmaker' => 'Ražotājs',
  'Sysm Sysmakers' => 'Ražotāji',
  'Syss' => 'Uzņemuma Id',
  'Syss Ccmp' => 'Uzņēmums',
  'The requested page does not exist.' => 'Pieprasītā lapa neeksistē',
  'Update' => 'Labot',
  'View' => 'Skatīt',
);
